version: '3.4'

services:
  catalogdb:
    image: mongo
  cartdb:
    image: redis:alpine
  
  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  cart.api:
    image: ${DOCKER_REGISTRY-}cart
    build:
      context: .
      dockerfile: Services/Basket/Cart.API/Dockerfile

volumes:
    mongo_data:
    portainer_data:
    


